// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAPM.ResourceRegistryMS.Api.Migrations
{
    [DbContext(typeof(ResourceRegistryDbContext))]
    [Migration("20240403144028_DAPM_ResourceRegistry")]
    partial class DAPM_ResourceRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAPM.ResourceRegistryMS.Api.Models.Resource", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Repository_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Repository_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Resource_id")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
